kind: Deployment
apiVersion: apps/v1
metadata:
  name: k8s-java-springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-springboot-app
  template:
    metadata:
      labels:
        app: k8s-springboot-app
    spec:
      containers:
        - name: k8s-java-springboot
          image: dotiendat1751998/k8s-springboot-series:latest
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              memory: "180Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: k8s-springboot
spec:
  ports:
    - name: http-8081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: k8s-springboot
