apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-springboot-series # Tên của ReplicationController
spec:
  replicas: 3 # Số lượng Pod muốn chạy tại một thời điểm.
  selector:
    app: k8s-series # Label sử dụng để tim các pods để quản lý.
  template: # Phần này định nghĩa podTemplate để ReplicationController tạo.
    metadata:
      name: k8s-springboot-series
      labels:
        app: k8s-series
    spec:
      containers:
        - name: k8s-springboot-series
          image: dotiendat1751998/k8s-springboot-series:latest
          ports:
            - containerPort: 8080

