apiVersion: v1
kind: Pod
metadata:
  name: k8s-springboot-series
  labels:
    app: k8s-springboot-series
spec:
  containers:
    - name: k8s-springboot-series
      image: dotiendat1751998/k8s-springboot-series:latest
      ports:
        - containerPort: 8088
          name: http
  restartPolicy: Always
